// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7kczR6r_K4p8H8hF7zILKvPt5dlT6f0M',
    appId: '1:972709481947:web:31f78eac67cb21a3b6ebfe',
    messagingSenderId: '972709481947',
    projectId: 'swivel-event-planner-7c5e7',
    authDomain: 'swivel-event-planner-7c5e7.firebaseapp.com',
    storageBucket: 'swivel-event-planner-7c5e7.firebasestorage.app',
    measurementId: 'G-PB52RVL1LH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9Y_yKQa5AVCcxGeedLhK_-a8YyyG6sDE',
    appId: '1:972709481947:android:04b3cd9c888a9212b6ebfe',
    messagingSenderId: '972709481947',
    projectId: 'swivel-event-planner-7c5e7',
    storageBucket: 'swivel-event-planner-7c5e7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLcp8kJAVLAzJWVOiDJBqodsBCgWbcHLE',
    appId: '1:972709481947:ios:e0719ff2597fa609b6ebfe',
    messagingSenderId: '972709481947',
    projectId: 'swivel-event-planner-7c5e7',
    storageBucket: 'swivel-event-planner-7c5e7.firebasestorage.app',
    iosBundleId: 'com.example.eventPlannerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLcp8kJAVLAzJWVOiDJBqodsBCgWbcHLE',
    appId: '1:972709481947:ios:e0719ff2597fa609b6ebfe',
    messagingSenderId: '972709481947',
    projectId: 'swivel-event-planner-7c5e7',
    storageBucket: 'swivel-event-planner-7c5e7.firebasestorage.app',
    iosBundleId: 'com.example.eventPlannerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7kczR6r_K4p8H8hF7zILKvPt5dlT6f0M',
    appId: '1:972709481947:web:957218c63987f6d9b6ebfe',
    messagingSenderId: '972709481947',
    projectId: 'swivel-event-planner-7c5e7',
    authDomain: 'swivel-event-planner-7c5e7.firebaseapp.com',
    storageBucket: 'swivel-event-planner-7c5e7.firebasestorage.app',
    measurementId: 'G-PBEV57BZ55',
  );
}
